[package]
name = "ThreadPool"
version = "0.1.0"
authors = ["Marcio Ordonez <marcio.v.ordonez@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
